package fr.olivierrevial.microservices.documentation;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;

import fr.olivierrevial.microservices.web.SampleControllerIT;

/**
 * Test suite to make sure Swagger documentation is generated by the
 * integration test after and only after all documentation snippets tests
 * have run. DocumentationIT should always run after all the other tests
 * generating doc examples !
 */
@RunWith(Suite.class)
@Suite.SuiteClasses({
        SampleControllerIT.class,
        DocumentationIT.class })
public class DocumentationTestSuiteIT {

}
